// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbkfhahgigpzodmgsysl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZia2ZoYWhnaWdwem9kbWdzeXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTA0NzMsImV4cCI6MjA3MzgyNjQ3M30.cxbNYDIjHvZE1jqr-1AFKcFzn78WftcfAnwvY4EiD3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});